### ISSUE TITLE
Laravel\Socialite\Two\InvalidStateException in GET /github/callback

### ISSUE THREAD

**Issue by georgeburdell** [RoboJackets/apiary#1344]
## Error in Apiary

**Laravel\Socialite\Two\InvalidStateException** in **GET /github/callback**

[View on Bugsnag](https://app.bugsnag.com/robojackets/apiary/errors/5f5924e64292530017bc75c0?event_id=5f5924e6005ebb060cfb0000&i=gh&m=ci)

## Stacktrace

    app/Http/Controllers/GitHubController.php:47 - App\Http\Controllers\GitHubController::handleProviderCallback
    app/Http/Middleware/CASAuthenticate.php:143 - App\Http\Middleware\CASAuthenticate::handle

[View full stacktrace](https://app.bugsnag.com/robojackets/apiary/errors/5f5924e64292530017bc75c0?event_id=5f5924e6005ebb060cfb0000&i=gh&m=ci)

*Created by RoboJackets Admin via Bugsnag*

**Comment by kberzinch** [comment]
This happens if the user declines access

https://my.robojackets.org/github/callback?error=access_denied&error_description=The%20user%20has%20denied%20your%20application%20access.&error_uri=https%3A%2F%2Fdocs.github.com%2Fapps%2Fmanaging-oauth-apps%2Ftroubleshooting-authorization-request-errors%2F%23access-denied&state=redacted
