### ISSUE TITLE
Remove demographics data

### ISSUE THREAD

**Issue by kberzinch** [RoboJackets/apiary#548]
To discuss with management

**Comment by kberzinch** [comment]
cc @JasonGibson274 @jspalten

**Comment by jspalten** [comment]
I'd like to still get some amount of data from everyone during dues processing, because that greatly increases our sample size, meaning we have a fuller idea of our organization as a whole, whereas on our demographics survey (IIRC) there's a much smaller response pool just because of response bias.

**Comment by jspalten** [comment]
I understand we want to avoid associating names with some data we collect in the demographics survey, but, again, we get much less data that way just because people have the option to not respond. I don't have a very good solution, so I guess just keeping data we're comfortable having associated with names and high-impact data as dues process data and the rest in the bigger demographics survey would work, but then we need to figure out what those are

**Comment by kberzinch** [comment]
Per discussion in Slack, we would like to continue collecting basic data during dues flow, so closing this issue.
